'use strict';
const $=s=>document.querySelector(s);let E=window.GUIDE.events;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=u=>{try{const v=new URL(u);return /^https?:$/.test(v.protocol)?v.href:'#';}catch{return '#';}};
const today=(now=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
function status(e,now=new Date()){if(e.planning)return '下一届待通知';if(e.archive)return '已截止';if(!e.verified)return '待核实';if(e.end&&(e.dateType==='datetime'?now.getTime()>=Date.parse(e.end):today(now)>e.end))return '已截止';if(!e.end||!e.start)return '待核实';return (e.start.length>10?now.getTime()<Date.parse(e.start):today(now)<e.start)?'即将开始':'正在报名';}
let saved=[];try{let v=JSON.parse(localStorage.getItem('qingshan-saved-v1')||'[]');if(Array.isArray(v))saved=v.filter(id=>E.some(e=>e.id===id));}catch{}
let category='',view='all',toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2200);}
function toggleSave(id){if(!E.some(e=>e.id===id))return;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem('qingshan-saved-v1',JSON.stringify(saved));toast(saved.includes(id)?'已加入收藏':'已取消收藏');}catch{toast('浏览器无法保存，收藏仅在本次访问保留');}render();}
const shortDate=s=>s?s.slice(0,10).replaceAll('-','.'):'';
function timing(e){const s=status(e);if(e.planning)return ['备赛计划',e.planningYear?e.planningYear+' · 待通知':'当届通知待核实'];if(s==='即将开始')return ['报名开始',shortDate(e.start)];if(s==='正在报名')return ['报名截止',shortDate(e.end)];if(s==='已截止')return ['本届报名已结束',e.end?shortDate(e.end):'各校时间不同'];return ['报名时间','待官方确认'];}
function group(e,now=new Date()){const s=status(e,now);return s==='正在报名'?0:s==='即将开始'?1:s==='下一届待通知'?2:3;}
function visible(e){return ['正在报名','即将开始','下一届待通知'].includes(status(e));}
function order(a,b){return group(a)-group(b)||($('#sort').value==='name'?a.name.localeCompare(b.name,'zh-CN'):(Date.parse(a.end)||Infinity)-(Date.parse(b.end)||Infinity))||a.rank-b.rank;}
function filtered(){let query=$('#search').value.trim().toLowerCase(),region=$('#region').value,st=$('#status').value;return E.filter(e=>visible(e)&&(!query||[e.name,e.short,e.edition,e.organizer,e.category,e.track].join(' ').toLowerCase().includes(query))&&(!category||e.category===category)&&(!region||e.region.includes(region))&&(!st||status(e)===st)&&(view!=='saved'||saved.includes(e.id))).sort(order);}
function card(e){let st=status(e),date=timing(e);return `<article class="card" data-event="${e.id}"><div class="card-top"><span class="event-icon" aria-hidden="true">${esc(e.category==='创新创业'?'创':e.category==='调研分析'?'研':'艺')}</span><span class="badge ${st==='即将开始'?'upcoming':st==='正在报名'?'open':''}">${st}</span><button class="save" data-save="${e.id}" aria-label="${saved.includes(e.id)?'取消收藏':'收藏'} ${esc(e.short)}" aria-pressed="${saved.includes(e.id)}">${saved.includes(e.id)?'★':'☆'}</button></div><h3><button data-detail="${e.id}">${esc(e.name)}</button></h3><p class="edition">${esc(e.edition)}</p><p class="summary">${esc(e.summary)}</p><div class="tags"><span>${esc(e.category)}</span><span>${esc(e.region)}</span></div><div class="card-foot"><div><span class="date-caption">${date[0]}</span><span class="date-value">${date[1]}</span></div><button class="detail-link" data-detail="${e.id}">查看详情 ↗</button></div></article>`;}
function render(){let list=filtered();$('#count').textContent=list.length+' 项';$('#savedCount').textContent=saved.filter(id=>E.some(e=>e.id===id&&visible(e))).length;$('#listTitle').firstChild.textContent=view==='saved'?'我的收藏 ':'发现赛事 ';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category===category);b.setAttribute('aria-pressed',String(b.dataset.category===category));});const groups=[['正在报名','',[0]],['即将开始','官方赛程已公布',[1]],['提前准备','下一届时间与规则待通知',[2]]];$('#results').innerHTML=list.length?groups.map(([title,note,ids],i)=>{let arr=list.filter(e=>ids.includes(group(e)));return arr.length?`<section class="${i===2?'planning':''}"><h3 class="group-title">${title}<small>${note}</small></h3><div class="grid">${arr.map(card).join('')}</div></section>`:'';}).join(''):`<div class="empty"><b>${view==='saved'&&!saved.length?'还没有收藏的赛事':'暂时没有符合条件的赛事'}</b><p>${view==='saved'&&!saved.length?'点击赛事卡片上的星标，留住感兴趣的比赛。':'试试其他关键词，或调整筛选条件。'}</p><button data-reset>查看全部赛事</button></div>`;}
const section=(title,content)=>`<section class="detail-section"><h3>${esc(title)}</h3><p>${esc(content)}</p></section>`;
function details(id){const e=E.find(e=>e.id===id);if(!e||!visible(e))return;const d=timing(e);$('#detailBody').innerHTML=`<p class="eyebrow">${esc(e.category)} / ${esc(e.region)}</p><h2 id="detailTitle">${esc(e.name)}</h2><p class="lead">${esc(e.edition)}</p><div class="detail-date"><span>${d[0]}</span><b>${d[1]}</b><span>${status(e)}</span></div>${section('赛事介绍',e.summary)}${e.preparation?section('备赛建议',e.preparation):''}${section('主办方',e.organizer)}${section('参赛方向',e.track)}${section('参赛资格',e.qualification)}${section('报名方式',e.route)}<section class="detail-section"><h3>赛程安排</h3><ul>${e.milestones.map(m=>'<li>'+esc(m)+'</li>').join('')}</ul></section>${section('提交材料',e.materials)}${section('参赛费用',e.fee)}${section('赛事背景',e.recognition)}<section class="detail-section"><h3>官方通知与参考来源</h3>${e.sources.map(s=>`<p><a href="${esc(safeURL(s.url))}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><br><small>${esc(s.scope)} · ${esc(s.note)}</small></p>`).join('')}<small>整理日期：${esc(e.verifiedAt)}</small></section><div class="detail-actions"><a href="${esc(safeURL(e.website))}" target="_blank" rel="noopener">${e.planning?'查看赛事来源':'官方赛事与报名'} ↗</a><a class="secondary" href="${esc(safeURL(e.sources.find(s=>s.url.endsWith('.pdf'))?.url||e.sources[0].url))}" target="_blank" rel="noopener">${e.planning?'查看往届参考':'查看正式通知'} ↗</a><button data-save="${e.id}">收藏 / 取消收藏</button></div>`;$('#detail').setAttribute('aria-labelledby','detailTitle');if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;}
function reset(){category='';view='all';$('#search').value='';$('#region').value='';$('#status').value='';$('#sort').value='date';render();}
$('#verified').textContent=shortDate(window.GUIDE.verified);
$('#categories').innerHTML=['全部赛事',...new Set(E.map(e=>e.category))].map((c,i)=>`<button class="category${i?'':' active'}" data-category="${i?esc(c):''}" aria-pressed="${!i}">${esc(c)}</button>`).join('');
$('#search').addEventListener('input',render);for(const id of ['region','status','sort'])$('#'+id).addEventListener('change',render);
$('#searchForm').onsubmit=event=>{event.preventDefault();render();$('#catalog').scrollIntoView({behavior:'smooth'});};$('#reset').onclick=reset;$('#close').onclick=()=>$('#detail').close();
$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){let r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.detail)details(d.detail);if(d.save)toggleSave(d.save);if('category'in d){category=d.category;render();}if(d.view){view=d.view;render();$('#catalog').scrollIntoView({behavior:'smooth'});}if(d.search){$('#search').value=d.search;category='';view='all';$('#region').value='';$('#status').value='';render();$('#catalog').scrollIntoView({behavior:'smooth'});}if('reset'in d)reset();});
render();setInterval(render,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});

let refreshing=false;async function refreshData(){if(refreshing)return;refreshing=true;try{const response=await fetch('events.json',{cache:'no-store'});if(!response.ok)throw Error('data unavailable');const next=await response.json();if(!Array.isArray(next.events)||!next.events.every(e=>e.id&&e.name&&Array.isArray(e.sources)&&Array.isArray(e.milestones)))throw Error('invalid data');E=next.events;window.GUIDE=next;$('#verified').textContent=shortDate(next.verified);render();}catch{document.querySelector('.updated').title='更新连接暂不可用，当前显示最近保存的核验数据';}finally{refreshing=false;}}refreshData();setInterval(refreshData,300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshData();});
